Show embedded entities on the catalog view
inmanta/web-console pull request #3273
Opened 2022-04-05 11:43 UTC by andraskvr

# Description

closes #3214 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Code is clear and sufficiently documented
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [x] ~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-04-07 13:54 UTC, FloLey requested changes
I think this looks good. I like to add 'public' everywhere just for consistency. I find the test really useful and easy to understand and they help to understand the code.

2022-04-07 13:54 UTC, FloLey commented on src/UI/Components/TreeTable/Catalog/AttributeHelper.ts
> +  getPaths(container: CatalogAttributeTree["source"]): string[] {
public getPaths?

2022-04-07 14:12 UTC, andraskvr commented on src/UI/Components/TreeTable/Catalog/TreeTableHelper.ts
> +export class CatalogTreeTableHelper implements TreeTableHelper {
I'll check again, it's a good suggestion

2022-04-07 15:06 UTC, FloLey commented on src/Slices/ServiceCatalog/UI/Tabs/AttributeTable.stories.tsx
> +import React from "react";
I didn't know this, this is so cool :p

2022-04-08 06:07 UTC, inmantaci commented
Processing this pull request

2022-04-08 06:07 UTC, inmantaci commented
Merged into branches iso5, master in c0f92e57ca09fe8d72841a78544d81538d054b72

2022-04-08 06:07 UTC, closed without merging