[FIX] remove reviewer checklist
inmanta/web-console pull request #4406
Opened 2022-12-06 13:15 UTC by Hugo-Inmanta

# Description

remove reviewer checklist

part of https://github.com/inmanta/inmanta-core/issues/5005

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Code is clear and sufficiently documented
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-12-06 13:30 UTC, LauraStordeur commented
Why are we removing the reviewer checklist from the web-console? 😄

2022-12-06 13:42 UTC, Hugo-Inmanta commented
We're removing it from all repos since it wasn't being used much in practice. But if it is actually being used for this repo I won't remove it here.

2022-12-06 13:53 UTC, LauraStordeur commented
all good, we don't really use it ;)

2022-12-07 06:44 UTC, arnaudsjs requested changes

2022-12-07 06:44 UTC, arnaudsjs commented on changelogs/unreleased/5005-delete-reviewer-part-of-PR-checklist.yml
> +change-type: patch
```suggestion
issue-nr: 5005
issue-repo: inmanta-core
change-type: patch
```

2022-12-07 09:51 UTC, arnaudsjs approved these changes

2022-12-07 10:30 UTC, inmantaci commented
Processing this pull request

2022-12-07 10:31 UTC, closed without merging

2022-12-07 10:45 UTC, inmantaci commented
Processing #4412.