Issue/5949 th warnings
inmanta/web-console pull request #6016
Opened 2024-10-28 09:35 UTC by matborowczyk

# Description

Remove the errors about the accesibility of empty Table Headers - Service Inventory has still some warning, but as redesign will remove most of the tables from that view

closes #5949 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Code is clear and sufficiently documented
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2024-11-05 10:16 UTC, LukasStordeur commented
Considering you are applying the changes to ISO-7, please also resolve the warnings in the Service Inventory. It shouldn't be much more work I believe.

2024-11-05 10:19 UTC, LukasStordeur requested changes

2024-11-05 10:19 UTC, LukasStordeur commented on src/UI/words.tsx
> +  "common.emptyColumnHeader": "Empty Column Header",
Considering this is for accessiblity reasons, it should state what the collumn is about. 
```suggestion
  "common.emptyColumnHeader": "Column header for collapsible-expandable action",
```

2024-11-05 10:19 UTC, LukasStordeur commented on src/Slices/CompileDetails/UI/CompileStageReportTable.tsx
> +          <Th aria-hidden key="toggle" aria-label="tableHeader-toggle" />
Why is this one without screenReaderText?

2024-11-05 14:23 UTC, matborowczyk commented
![Screenshot 2024-11-05 at 15 11 09](https://github.com/user-attachments/assets/23bd4914-6435-4614-b7bf-c805424a9911)

2024-11-05 14:41 UTC, LukasStordeur commented on changelogs/unreleased/5949-th-warnings.yml
> +issue-nr: 5942
I think you made a typo in the ticket-number

2024-11-05 14:45 UTC, LukasStordeur commented on src/Slices/ServiceInventory/UI/InventoryTable.tsx
> +        screenReaderText={
You can simply add the attribute in the line above like so:

```TS
{...(column.apiName === "actions" && { 
  "aria-hidden": true, 
  "screenReaderText": words("common.emptyColumnHeader") 
})}
```

2024-11-06 12:27 UTC, LukasStordeur approved these changes

2024-11-06 12:27 UTC, LukasStordeur commented on src/Slices/CompileDetails/UI/CompileStageReportTable.tsx
> +            aria-hidden
just found out that the aria-hidden isn't needed when adding the screenReaderText, no need to make the changes, just an FIY

2024-11-06 14:01 UTC, inmantaci commented
Processing this pull request

2024-11-06 14:01 UTC, inmantaci commented
Pull request rejected by merge tool. The tests for this branch did not succeed.

2024-11-06 15:07 UTC, inmantaci commented
Merged into branches master in 4e9bf8b656c0c9d61d19fc6bf795a3cf927ab780

2024-11-06 15:07 UTC, closed without merging